




let arr = [
    {
        name: "test",
      key: 1,
    },
    {
      name: "task",
      key: 2,
    },
    {
      name: "tanqo",
      key: 3,
    },
    {
      name: "like",
      key: 4,
    },
    {
      name: "task",
      key: 5,
    },
    {
      name: "trust",
      key: 6,
    },
    {
      name: "test",
      key: 7,
    },
    {
      name: "last",
      key: 8,
    },
    {
      name: "tanqo",
      key: 9,
    },
    {
      name: "elephant",
      key: 10,
    },
    {
      name: "love",
      key: 11,
    },
    {
      name: "small",
      key: 12,
    },
    {
      name: "little",
      key: 13,
    },
  ];
  // TASK1
// let herf = arr.filter((array) =>
// array.name.trim().toLowerCase().startWith("t".trim().toLowerCase())
// );
// console.log(herf);
// TASK2
// let res = arr.filter(
//     (number) =>
//     number.name.trim().toLowerCase().startsWith("t") &&
//     number.name.trim().toLowerCase().endsWith("t")
// );
// console.log(res);
// TASK3
// let sum=0
// arr.forEach(
//     (number) =>
//  {
//     if(number.name.trim().toLowerCase().startsWith("t") &&
//     number.name.trim().toLowerCase().endsWith("t")){
//         sum+=number.key
//     }
//  }
    
// );
// console.log(sum);
// TASK4
// arr.forEach(Obyect);
// function Obyect(item){
//     if( item.name.trim().toLowerCase().endsWith("e".trim().toLowerCase())){
//         item.name = "SuperDev";
//     }else{

//     }
// }
// console.log(arr);
// TASK5
// let maxElem = arr[0];
// let maxIndex = 0;
// arr.forEach((item,index,array)) => {
//     if(item.name.length>maxElem.length){
//         maxElem = item;
//         maxIndex = index;
//     }
// }
// console.log(maxElem.key);




